### ISSUE TITLE
Compatibilité WFS avec Geoide-carto

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#11]
### Type de diffusion concernée

Service WMTS / TMS

### Accès concerné

Ouvert

### Description de l'erreur

La DREAL-N indique que sur le front Geoide-carto, les styles du WFS ne sont pas appliqués.
https://carto2.geo-ide.din.developpement-durable.gouv.fr/frontoffice/?map=a57b7578-3233-4de7-870b-812756fbcd9e 

Anomalie lié au front ou problème de compatibilité du service?

**Comment by Dolite** [comment]
Je ne pense pas que le WFS puisse être en cause : le format des données retournées est indépendant de ce qui en est fait derrière. Mais si un champ a changé de nom, le WFS le retourne ainsi et le style s'appuyant sur ce champ peut ne plus marcher. Je ne vois pas les requêtes WFS dans le lien du ticket.

**Comment by jpotel** [comment]
Le problème vient de géoIDE Carto. Sur cette outil il est possible de donner une symbologie au flux WFS via l'interface de production de la carte mais ce style n'est pas repris dans la carte publiée.
