### ISSUE TITLE
WMS compatibilité du getfeatureinfo avec Geoide-Carto

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#12]
### Type de diffusion concernée

Service WMTS / TMS

### Accès concerné

Ouvert

### Description de l'erreur

La DREAL-N a constaté qu'il y a avait un souci d'encodage lors des interrogations des objets de la couche
https://carto2.geo-ide.din.developpement-durable.gouv.fr/frontoffice/?map=a57b7578-3233-4de7-870b-812756fbcd9e

**Comment by Dolite** [comment]
En WFS on a bien les accents, ce qui me fait dire que l'encodage des données est bon (c'est déjà ça). Avec le getFeatureInfo, on a aussi le problème de l'encodage du contenant (plain/text ou html...). Je 'arrive pas à avoir d'exemple de requête, c'est possible d'en avoir un ?

**Comment by jpotel** [comment]
Voici un exemple de requête : 

https://data.geopf.fr/wms-v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&CRS=EPSG:3857&WIDTH=1672&HEIGHT=742&BBOX=-43669.602536,6286429.222,-20347.320097,6296779.182269&LAYERS=l_parc_s_r28&QUERY_LAYERS=l_parc_s_r28&I=1065&J=487&INFO_FORMAT=text%2Fhtml

A l'affichage on voit bien les accents. Les données apparaissent bien avec des accents par contre le fichier html ne contient pas d'information sur l'encodage utilisé.

**Comment by Dolite** [comment]
Geoserver ne met effectivement pas d'encodage dans le head html par défaut. On va voir pour modifier le header.ftl par défaut au niveau du service avec :

```
<#--
Header section of the GetFeatureInfo HTML output. Should have the <head> section, and
a starter of the <body>. It is advised that eventual css uses a special class for featureInfo,
since the generated HTML may blend with another page changing its aspect when using generic classes
like td, tr, and so on.
-->
<html>
  <head>
    <title>GeoServer GetFeatureInfo output</title>
    <meta charset="utf-8">
  </head>
  <style type="text/css">
        table.featureInfo, table.featureInfo td, table.featureInfo th {
                border:1px solid #ddd;
                border-collapse:collapse;
                margin:0;
                padding:0;
                font-size: 90%;
                padding:.2em .1em;
        }
        table.featureInfo th{
            padding:.2em .2em;
                text-transform:uppercase;
                font-weight:bold;
                background:#eee;
        }
        table.featureInfo td{
                background:#fff;
        }
        table.featureInfo tr.odd td{
                background:#eee;
        }
        table.featureInfo caption{
                text-align:left;
                font-size:100%;
                font-weight:bold;
                text-transform:uppercase;
                padding:.2em .2em;
        }
  </style>
  <body>
```

**Comment by Dolite** [comment]
Le plus important est que les données soient bien encodées en base, et que geoserver les interprète bien. Sur quel logiciel avez vous le souci ?

**Comment by Dolite** [comment]
Avez vous pu trouver une solution côté client ? Nous avons fait la demande de forcer l'encodage UTF-8 côté service.

**Comment by jpotel** [comment]
J'ai fait remonter l'information du problème.

**Comment by Dolite** [comment]
L'encodage UTF-8 est désormais bien précisé dans les réponses au GetFeatureInfo au format HTML. Désolé pour l'oubli de réponse ici.
