### ISSUE TITLE
Quotas trop limitatifs

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#13]
### Entité(s) concernée(s)

endpoint

### Route API concernée

None

### Méthode de la route API

None

### Description détaillée du bug

La DREAL-N indique que le quota de 10 est trop limitant par rapport à ses 200 couches déjà diffusées.
Par ailleurs, un endpoint associée à la DREAL-N est nécessaire pour ne disposer que des 200 couches de la DREAL-N et pas de toutes celles de la GPF.

**Comment by Dolite** [comment]
Nous allons mettre des quotas cohérents avec les besoins. Pour avoir seulement ses couches sur un endpoint ouvert, il est possible de mettre en place un getcapabilities personnalisé statique : https://geoplateforme.github.io/tutoriels/divers/thematique/ . Avoir son propre endpoint est possible mais implique des actions plus lourdes. Si ce n'est que pour avoir un getcap dédié, la solution précédente est suffisante et le partenaire est complètement autonome.

**Comment by Dolite** [comment]
Sur quel type de diffusion sont les 200 couches ?

**Comment by IGNF-Xavier** [comment]
A vérifier avec la DREAL-Normandie mais il est fort probable que cela corresponde aux couches aujourd'hui visualisables à cette adresse : https://www.normandie.developpement-durable.gouv.fr/les-cartes-interactives-a4661.html

**Comment by Dolite** [comment]
C'est du WMS raster, et ce endpoint n'est pas officiellement disponible. Je ne pense pas que les couches aient déjà été mises en place, mais le endpoint sera ajouté à ce moment là (avec des quotas adéquats).
