### ISSUE TITLE
Tag sur route metadata

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#14]
### Documentation concernée

Gestion des métadonnées

### Description du manque de détail

Après avoir réalisé la demande de tag sur la route metadata (https://github.com/Geoplateforme/geoplateforme.github.io/issues/2), il faudra enrichir la documentation API sur cette route pour que l'utilisateur mette bien des tags qui permettraient d'identifier la métadonnée à sa donnée.

Le cas échéant, les  IHM de catalogue et d'alimentation/diffusion seront dans l'incapacité d'exposer lesdites données

**Comment by Dolite** [comment]
Lors de la configuration de la diffusion, on peut mettre des métadonnées pour avoir le lien entre la couche et la métadonnée. Le lien au niveau de la stored data ne serait pas visible le consommateur de données.

**Comment by Dolite** [comment]
Une demande d'évolution sur la gestion des métadonnées existait et les deux besoins peuvent fusionner, j'ai ajouté les spécifications qui vous conviendraient.

**Comment by slafayIGN** [comment]
> Lors de la configuration de la diffusion, on peut mettre des métadonnées pour avoir le lien entre la couche et la métadonnée. Le lien au niveau de la stored data ne serait pas visible le consommateur de données.

Dans `POST /datastores/{datastore}/configurations`

Une partie du body contient en effet des informations sur la métadonnée liée :
```json
"metadata": [
    {
      "format": "application/xml",
      "url": "string",
      "type": "ISO19115:2003"
    }
  ]
  ```
  
  Ce lien décrit ainsi est pratique pour les applications clientes des flux mais ce n'est pas un lien direct entre les entités `configuration` et `metadata` de l'API Entrepôt.

**Comment by Dolite** [comment]
Il n'y aura pas de lien natif entre les deux, ce sera juste un usage des tags qui permettront à une application cliente de gérer des liens comme ça.
