### ISSUE TITLE
A quoi sert l'attribut "open" dans la demande de publication d'une offre ?

### ISSUE THREAD

**Issue by jpotel** [Geoplateforme/geoplateforme.github.io#15]
### Vos questions

Bonjour,

Dans la publication d'une offre `POST /datastores/{datastore}/configurations/{configuration}/offerings` que signifie concrètement les attributs "open", "visibiliy" ?

![image](https://github.com/Geoplateforme/geoplateforme.github.io/assets/34372864/66a6392d-2e5c-4fc8-b6ba-28f658979f06)

"visibility" pour communiquer ou non sur l'existence de l'offre et "open" pour restreindre ou non l'accès à l'offre ?

Faut-il jouer sur "open" pour créer des permissions d'accès aux services ?

Merci d'avance pour votre réponse

**Comment by Dolite** [comment]
La notion de visibilité pour les offres va disparaître prochainement. La notion open permet de rendre une offre sur un endpoint **restreint** accessible sans avoir à définir des permissions.
Sur un endpoint open, l'attribut open de l'offre n'est pas pris en compte (toutes les offres sur un endpoint open sont open, c'est à dire utilisables sans définir de permissions).
