### ISSUE TITLE
le lien vers le catalogue de donnée ne fonctionne pas

### ISSUE THREAD

**Issue by jpotel** [Geoplateforme/geoplateforme.github.io#17]
### Tutoriel concerné

None

### Page concernée

https://geoplateforme.github.io/tutoriels/complement/metadonnees/publication/

### Description de l'erreur

Quand je clique sur le lien "interface web du catalogue" (https://data.geopf.fr/catalog.search#/search?any=IGNF_RGEALTIr_2-0_ASC_5M_LAMB93_IGN69_D074.xml) j'arrive sur une page avec un json en retour
`{
    "message": "no Route matched with those values"
}`

**Comment by Dolite** [comment]
L'interface graphique de Geonetwork n'est plus accessible. Seul le CSW est disponible (documentation mise à jour). Une nouvelle interface sera mise à disposition (via datahub).

**Comment by jpotel** [comment]
savez vous à quel horizon l'interface de consultation sera disponible ?
Sinon pour rester  sur le tutoriel le lien [GetRecordById](https://data.geopf.fr/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&ID=IGNF_RGEALTIr_2-0_ASC_5M_LAMB93_IGN69_D074.xml) présent ne renvoie rien. Il n'existe pas dans le csw de ressource avec l'identifiant IGNF_RGEALTIr_2-0_ASC_5M_LAMB93_IGN69_D074.xml.
La seule donnée semblant être présente ou diffusée au niveau internet via le csw est IGNF_GEOFLA_45.xml
(cf. [https://data.geopf.fr/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&typeNames=gmd:MD_Metadata&resultType=results&ElementSetName=full](https://data.geopf.fr/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&typeNames=gmd:MD_Metadata&resultType=results&ElementSetName=full))

**Comment by IGNF-Xavier** [comment]
Bonjour,
Pour l'interface de consultation des métadonnées, nous envisageons une ouverture pour fin d'année 2023 mais il y a plusieurs conditions à réunir (en cours) :

- une autorisation d'accès à Geonetwork par l'instance datahub que nous utiliserons. C'est un sujet associé à l'infrastructure.
- déploiement sur l'environnement de production, sujet basique de déploiement.
- mise à niveau des métadonnées de données, en cours et à associer aussi aux travaux de bascule des données et services de l'infrastructure Géoportail à celle de la Géoplateforme.
