### ISSUE TITLE
échec execution error 400

### ISSUE THREAD

**Issue by Inrap** [Geoplateforme/geoplateforme.github.io#18]
### Entité(s) concernée(s)

check execution

### Route API concernée

/datastores/{datastore}/checks/executions

### Méthode de la route API

POST

### Description détaillée du bug

bonjour,

En utilisant les données fournies, je bloque sur l'étape du tutoriel fourni _Configuration d'une exécution de ce traitement_ ->` POST /datastores/{datastore}/processings/executions`

qui renvoie **l'erreur 400** correspondant à un défaut des données en entrée et un tableau vide 🤔.

Dans le corps de la requête du tuto :

    {
        "processing": "0de8c60b-9938-4be9-aa36-9026b77c3c96",
        "inputs": {
            "upload": [
                "{upload}"
            ]
    },
    "output": {
        "stored_data": {
            "name": "Pays et éco-régions",
            "storage_tags": ["VECTEUR"]
        }
    },
    "parameters": {
        "srs": "EPSG:3857"
     }
    }

- J'ai remplacé la variable `{upload}` par celle fournie avec `GET/datastores/{datastore}/uploads`.

- Le numéro du processing est identique.

Je suis visiblement passé à coté d'autres paramétrages.
Pouvez-vous m'éclairer ?

**Comment by Inrap** [comment]
résolu.
Je ne sais pas exactement comment, mais c'est passé au final.

**Comment by Dolite** [comment]
Tant mieux. N'hésitez pas à refaire un ticket si cela devait se reproduire.
