### ISSUE TITLE
Communauté - description

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#20]
### Entité(s) concernée(s)

community

### Route API concernée

None

### Méthode de la route API

None

### Description détaillée du fonctionnement actuel

L'API prévoit que l'espace de travail corresponde à la communauté (community) et son entrepôt associé (datastore).
Il s'agit d'une relation 1-1 ou 1-0 puiqu'une communauté peut ne pas avoir de datastore.
Et un datastore peut contenir  un ensemble de données, fichiers statiques, configurations.

Je reprends les définitions car mon interrogation porte sur la mise en oeuvre d'une description associée à la communauté (qui forcément s'appliquera au datastore s'il existe).
Sauf erreur cette information "description" associée à la communauté n'est pas prévu dans l'API. Peut-on le prévoir?

### Description détaillée du fonctionnement proposé

Un paramètre "description" supplémentaire peut être renseigné en plus du nom de la communauté à sa création

**Comment by Dolite** [comment]
C'est une évolution assez simple et qui peut effectivement apporter une information importante, surtout pour les communautés publiques.

**Comment by Dolite** [comment]
Demande d'évolution prise en compte
