### ISSUE TITLE
Retour erreur serveur à la publication d'une métadonnée

### ISSUE THREAD

**Issue by jpotel** [Geoplateforme/geoplateforme.github.io#22]
### Type de diffusion concernée

Catalogue de métadonnées

### Accès concerné

Ouvert

### Description de l'erreur

Bonjour,

je souhaitais publier des métadonnées sur le csw de la geoplateforme mais je bloque au moment de la publication. 

La requête POST /datastores/{datastore}/metadata/publication me renvoie un code 500 avec la réponse json suivante : 

```
{
  "error": "Internal Server Error",
  "error_description": [
    "Erreur serveur"
  ]
}
```
Le problème vient-il de la structuration du fichier xml ? Celui-ci est issu de l'IDG Géoide du MTES.

ci après le xml concerné : [metadata_l_mat_eolien_p_r28.zip](https://github.com/Geoplateforme/geoplateforme.github.io/files/13166342/metadata_l_mat_eolien_p_r28.zip)

Cordialement

**Comment by Dolite** [comment]
Bug reproduit, le problème a été remonté.

**Comment by Dolite** [comment]
C'est corrigé. Vous pouvez confirmé ?

**Comment by jpotel** [comment]
Ca ne marche toujours pas mais le message à changé :
`
{
  "error": "Internal Server Error",
  "error_description": [
    "Erreur lors de la publication des métadonnées suivantes : fr-120066022-jdd-ebaa4945-19c3-45dd-88c0-35b1f091b608"
  ]
}
`

**Comment by Dolite** [comment]
Nous reprenons la surveillance de l'instabilité de la publication de métadonnée.

**Comment by Dolite** [comment]
A priori la métadonnée est déjà publiée, d'où l'erreur. On va probablement changer le code d'erreur pour retourner une erreur d'utilisation et non une erreur interne.
