### ISSUE TITLE
Publication en WFS

### ISSUE THREAD

**Issue by JulienDefe** [Geoplateforme/geoplateforme.github.io#23]
### Entité(s) concernée(s)

configuration, datastore

### Route API concernée

/datastores/{datastore}/configurations

### Méthode de la route API

POST

### Description détaillée du bug

Datastore 24111ff4-5bb1-4310-8308-adf754869714

Corps :
      {
        "type": "WFS",
        "name": "l_alea_minier_s_r28",
        "layer_name": "l_alea_minier_s_r28",
        "type_infos": {
            "bbox": {
                "west": -3,
                "south": 47,
                "east": 3,
                "north": 51
            },
            "used_data": [
                {
                    "relations": [
                        {
                            "native_name": "l_alea_minier_s_r28_v20231024",
                            "public_name": "l_alea_minier_s_r28_v20231024",
                            "title": "Les aléas miniers en Normandie",
                            "keywords": [
                                "Normandie", "alea minier"
                            ],
                            "abstract": "Les aléas miniers en Normandie"
                        },
                    "stored_data": "d83cd339-6bb7-4058-a73e-9f9e61d563b7"
                }
            ]
        }

Réponse :
 {
  "error": "Bad Request",
  "error_description": [
    "Le corps de la requête contient un élements non requis"
  ]
}
Je n'arrive pas à identifier le pb, j'ai à priori bien suivi la construction du corps de la requete depuis le tutoriels https://geoplateforme.github.io/tutoriels/vecteur/base/publication_wfs/
Seriez vous en mesure d'identifier le pb?
MErci

**Comment by Dolite** [comment]
Dans le corps de requête JSON, l'identifiant de stored data est dans le tableau relations, alors qu'il doit être à l'extérieur. Pour reprendre votre exemple, on devrait plutôt avoir le JSON suivant :

```json
{
    "type": "WFS",
    "name": "l_alea_minier_s_r28",
    "layer_name": "l_alea_minier_s_r28",
    "type_infos":
    {
        "bbox":
        {
            "west": -3,
            "south": 47,
            "east": 3,
            "north": 51
        },
        "used_data":
        [
            {
                "relations":
                [
                    {
                        "native_name": "l_alea_minier_s_r28_v20231024",
                        "public_name": "l_alea_minier_s_r28_v20231024",
                        "title": "Les aléas miniers en Normandie",
                        "keywords":
                        [
                            "Normandie",
                            "alea minier"
                        ],
                        "abstract": "Les aléas miniers en Normandie"
                    }
                ],
                "stored_data": "d83cd339-6bb7-4058-a73e-9f9e61d563b7"
            }
        ]
    }
}
```

**Comment by JulienDefe** [comment]
En effet, nickel code 201 je vais pourvoir avancer dans mes tests.
Merci pour la réactivité
