### ISSUE TITLE
Publication en WMS

### ISSUE THREAD

**Issue by JulienDefe** [Geoplateforme/geoplateforme.github.io#24]
### Documentation concernée

None

### Description du manque de détail

Pb pour publier en WMS une série de données déjà publier en WFS.

Avec POST /datastores/{datastore}/statics
J'ai déposé des fichiers statiques SLD (f1a3335b-c34b-428f-bf1e-90a572972c96)  et FTL (ce27cfb1-a360-4e06-acd2-9114492cb97e)  dans mon Datastores (24111ff4-5bb1-4310-8308-adf754869714)

Ensuite j'ai voulu configurer mon wms avec POST [/datastores/{datastore}/configurations]
J'ai une erreur 400 {
  "error": "Bad Request",
  "error_description": [
    "Le nom l_alea_minier_s_r28 ne correspond à aucune relation de la donnée stockée d83cd339-6bb7-4058-a73e-9f9e61d563b7"
  ]
}
Ai je oublié une étape? qui ne semble pas être dans le tuto.

Voici le corps de ma requête
{
    "type": "WMS-VECTOR",
    "name": "l_alea_minier_s_r28",
    "layer_name": "l_alea_minier_s_r28",
    "type_infos": {
        "title": "Aléas miniers de Normandie",
        "abstract": "Aléas miniers de Normandie",
        "keywords": [
            "aléa", "Normandie"
        ],
        "bbox": {
                "west": -3,
                "south": -47,
                "east": 3,
                "north": 51
        },
        "used_data": [
            {
                "relations": [
                    {
                        "name": "l_alea_minier_s_r28",
                        "style": "f1a3335b-c34b-428f-bf1e-90a572972c96",
                        "ftl": "ce27cfb1-a360-4e06-acd2-9114492cb97e"
                    }
                ],
                "stored_data": "d83cd339-6bb7-4058-a73e-9f9e61d563b7"
            }
        ]
    }
}

Merci

**Comment by JulienDefe** [comment]
Celle-ci, pour laquelle c'etati lié à une erreur de ma part.
https://github.com/Geoplateforme/geoplateforme.github.io/issues/24

**Comment by Dolite** [comment]
Pardon j'avais mal compris "issue", je n'étais pas sur le terme 'github'... Au temps pour moi.
