### ISSUE TITLE
Publication en WMS

### ISSUE THREAD

**Issue by JulienDefe** [Geoplateforme/geoplateforme.github.io#25]
### Type de diffusion concernée

Service WMS Vecteur

### Accès concerné

Ouvert

### Description de l'erreur

Lors de la demande de publication d'un flux 
Requête : POST datastore : /datastores/{datastore}/configurations/{configuration}/offerings
    
    Paramètre :
      datastore : 24111ff4-5bb1-4310-8308-adf754869714
      configuration : d14b43bc-562d-4fc6-b0c6-495128a48717
      
    Corps requête :
{
  "visibility": "PRIVATE",
  "endpoint": "ae022611-13eb-4a18-8d04-9b7604a031cc",
  "open": true
}
J'ai une Erreur 500 
{
  "error": "Internal Server Error",
  "error_description": [
    "Erreur serveur"
  ]
}

Ai je sauté une étape?

Merci

**Comment by Dolite** [comment]
Le problème est-il toujours d'acutalité ?

**Comment by JulienDefe** [comment]
Bonjour

Je n'ai rien modifié de mon côté, en relançant la requête c'est passé sans soucis ce matin...

**Comment by Dolite** [comment]
Il a pu y avoir une indisponibilité d'une brique impliquée dans la publication lors d'un redéploiement. Merci pour le nouveau test.
