### ISSUE TITLE
Livraisons et vérifications - check ?

### ISSUE THREAD

**Issue by grechg** [Geoplateforme/geoplateforme.github.io#27]
### Vos questions

Bonjour,
J'ai une requête /datastores/{datastore}/uploads/{upload}/checks qui passe mais qui indique 
"failed" pour la "Vérification vecteur".
Apparemment cela bloque la suite, mais comment corriger ?
Merci

**Comment by Dolite** [comment]
Pour avoir plus d'informations sur la raison de l'erreur, vous pouvez récupérer les logs de l'exécution de vérification avec son ID et la route GET /datastores/{id}/checks/executions/{id}. Attention à ne pas confondre avec l'identifiant de la vérification. Il faut que nous ajoutions cet usage dans les tutoriels. Si les logs ne permettent pas de comprendre ce qui pose problème, revenez vers nous et nous ferons évoluer cela.

**Comment by grechg** [comment]
Merci,
La requête me renvoie le json ci-dessous, ce qui je crois ne m'apporte pas l'explication.

name | "Vérification vecteur"
-- | --
_id | "66ed8a1b-93d9-4fe9-a413-ab93d31b2964"
status | "FAILURE"
creation | "2023-11-29T15:00:21.241250Z"
start | "2023-11-29T15:00:42.287920Z"
finish | "2023-11-29T15:02:19.781497Z"
upload |  
type | "VECTOR"
name | "string"
_id | "d285dbf4-31bb-4930-8a78-36a0b893741b"
_id | "205c9fb9-083d-42ee-a386-24a2146bf0a5"

**Comment by Dolite** [comment]
Au temps pour moi, la route est GET /datastores/{id}/checks/executions/{id}**/logs**. Sinon on ne récupère effectivement que les informations globales sur l'exécution.

**Comment by grechg** [comment]
J'ai un message :
2023-11-29 15:01:49,324ERROR||core||379||Paramètre SRS non valide sur la livraison
La couche est en 2154 ; cela pose t il un problème ?

**Comment by Dolite** [comment]
Il semblerait que le SRS détecté dans les fichiers livrés ne soit pas cohérent avec celui déclaré au niveau de la livraison. Vous avez mis EPSG:2154 dans la livraison, quel est le format des fichiers vecteurs livrés ? Êtes vous sur que ce soit la même ? Attention, IGNF:LAMB93 sera vu comme un SRS différent de EPSG:2154.

**Comment by grechg** [comment]
Oui, c'est bien le "RGF93 v1 / Lambert-93" (sous Qgis), dont l'id est bien "EPSG:2154"

**Comment by Dolite** [comment]
Pouvez vous me donner les informations sur votre livraison (la réponse au GET /datastores/{id}/uploads/{id}). Sinon pouvez vous m'envoyer vos données, ou un échantillon ?

**Comment by grechg** [comment]
{
  "name": "string",
  "description": "string",
  "type": "VECTOR",
  "visibility": "PRIVATE",
  "status": "CLOSED",
  "srs": "string",
  "contact": "grech@mnhn.fr",
  "size": 897970176,
  "last_event": {
    "title": "Vérification terminée",
    "text": "Vérification vecteur : Echec",
    "date": "2023-11-29T15:02:19.818541",
    "initiator": {
      "last_name": "wl",
      "first_name": "technical",
      "_id": "aa032611-13eb-4a18-8d04-9b7604a031cc"
    }
  },
  "tags": {},
  "_id": "d285dbf4-31bb-4930-8a78-36a0b893741b",
  "type_infos": {}
}
Je vous envoie les données par mail.

**Comment by Dolite** [comment]
Vous êtes passé par le swagger ? Du coup les champs name, description et srs sont avec les valeurs par défaut (donc le type du champ "string"). Le problème est là, il faut que vous modifiez les valeurs avec votre cas, et mettre une valeur pour le SRS qui correspondent aux données.

**Comment by grechg** [comment]
Ok, effectivement un raté.
J'ai tout repris et ça marche.
Merci pour tout !
