### ISSUE TITLE
Connexion à l'API Entrepôt via Python

### ISSUE THREAD

**Issue by ARainaud** [Geoplateforme/geoplateforme.github.io#29]
### Tutoriel concerné 
https://geoplateforme.github.io/tutoriels/vecteur/base/livraison/

### Description 
Lorsque je me connecte via mon navigateur web à l'url https://data.geopf.fr/api/users/me j'obtiens bien les information sur mon compte au format JSON avec, entre autre, un id pour le datastore qui m'a été assigné.

Cependant, lorsque j'utilise l'API avec python en suivant le tutoriel ci-dessus, notamment la requête POST /datastores/{datastore}/uploads avec mon id de datastore et ce corps de requête 
 {
    "description": "Températures (K) en France en Août 1950-2020",
    "name": "Températures Août France",
    "type": "VECTOR",
    "srs": "EPSG:4326"
}

J'obtiens un code réponse 200 et une page html correspondant certainement à cette page : https://sso.geopf.fr/realms/geoplateforme/protocol/openid-connect/auth?client_id=gpf-apim&state=0ea5072ccc7ce8fae28f07f8801daced&nonce=092392a41f965730bf948d70d2cbb658&redirect_uri=https%3A%2F%2Fdata.geopf.fr%2Fapi%2Fusers%2Fme%2F&scope=openid&response_type=code

Status code:  200
Printing Entire Post Request
<!DOCTYPE html>
<html class="login-pf" lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">

            <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <title>Se connecter à Géoplateforme</title>
    <link rel="icon" href="/resources/vhpbt/login/geoplateforme/img/favicon.ico" />
            <link href="/resources/vhpbt/common/keycloak/web_modules/@patternfly/react-core/dist/styles/base.css" rel="stylesheet" />
            <link href="/resources/vhpbt/common/keycloak/web_modules/@patternfly/react-core/dist/styles/app.css" rel="stylesheet" />
            <link href="/resources/vhpbt/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css" rel="stylesheet" />
            <link href="/resources/vhpbt/common/keycloak/node_modules/patternfly/dist/css/patternfly-additions.min.css" rel="stylesheet" />
            <link href="/resources/vhpbt/common/keycloak/lib/pficon/pficon.css" rel="stylesheet" />
            <link href="/resources/vhpbt/login/geoplateforme/css/login.css" rel="stylesheet" />
            <link href="/resources/vhpbt/login/geoplateforme/css/gpf.css" rel="stylesheet" />
            <script src="/resources/vhpbt/login/geoplateforme/js/jquery-3.6.4.js" type="text/javascript"></script>
            <script src="/resources/vhpbt/login/geoplateforme/js/gpf.js" type="text/javascript"></script>
            <script src="/resources/vhpbt/login/geoplateforme/js/node_modules/jquery-captcha/dist/jquery-captcha.min.js" type="text/javascript"></script>
</head>

<body class="">
<div class="login-pf-page">
    <div id="kc-header" class="login-pf-page-header">
        <div id="kc-header-wrapper"
             class="">Géoplateforme</div>
    </div>
    <div class="card-pf">
        <header class="login-pf-header">
                <div class="pf-c-dropdown" id="kc-locale">
                    <div id="kc-locale-wrapper" class="">
                        <div id="kc-locale-dropdown" class="">
                            <a href="#" id="kc-current-locale-link">Français</a>
                            <ul class="pf-c-dropdown__menu pf-m-align-right">
                                    <li class="">
                                        <a class="pf-c-dropdown__menu-item" href="/realms/geoplateforme/login-actions/authenticate?client_id=gpf-apim&amp;tab_id=-kMEH58m_EA&amp;execution=8b75e3a1-fe16-423f-befc-f452ec057c2f&amp;kc_locale=en">English</a>
                                    </li>
                                    <li class="">
                                        <a class="pf-c-dropdown__menu-item" href="/realms/geoplateforme/login-actions/authenticate?client_id=gpf-apim&amp;tab_id=-kMEH58m_EA&amp;execution=8b75e3a1-fe16-423f-befc-f452ec057c2f&amp;kc_locale=fr">Français</a>
                                    </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <h1 id="kc-page-title">        Connectez-vous à votre compte

</h1>
      </header>
      <div id="kc-content">
        <div id="kc-content-wrapper">

    <div id="kc-form">
      <div id="kc-form-wrapper">
            <form id="kc-form-login" onsubmit="login.disabled = true; return true;" action="https://sso.geopf.fr/realms/geoplateforme/login-actions/authenticate?session_code=_O5pHVgtq_dENREa6S1xhj9Bpaxix1SJpeXl7JWCqvw&amp;execution=8b75e3a1-fe16-423f-befc-f452ec057c2f&amp;client_id=gpf-apim&amp;tab_id=-kMEH58m_EA" method="post">
                    <div class="form-group">
                        <label for="username" class="pf-c-form__label pf-c-form__label-text">Nom d&#39;utilisateur ou courriel</label>

                        <input tabindex="1" id="username" class="pf-c-form-control" name="username" value=""  type="text" autofocus autocomplete="off"
                               aria-invalid=""
                        />

                    </div>

                <div class="form-group">
                    <label for="password" class="pf-c-form__label pf-c-form__label-text">Mot de passe</label>

                    <input tabindex="2" id="password" class="pf-c-form-control" name="password" type="password" autocomplete="off"
                           aria-invalid=""
                    />

                </div>

                <div class="form-group login-pf-settings">
                    <div id="kc-form-options">
                            <div class="checkbox">
                                <label>
                                        <input tabindex="3" id="rememberMe" name="rememberMe" type="checkbox"> Se souvenir de moi
                                </label>
                            </div>
                        </div>
                        <div class="">
                                <span><a tabindex="5" href="/realms/geoplateforme/login-actions/reset-credentials?client_id=gpf-apim&amp;tab_id=-kMEH58m_EA">Mot de passe oublié ?</a></span>
                        </div>

                  </div>

                  <div id="kc-form-buttons" class="form-group">
                      <input type="hidden" id="id-hidden-input" name="credentialId" />
                      <input tabindex="4" class="pf-c-button pf-m-primary pf-m-block btn-lg" name="login" id="kc-login" type="submit" value="Connexion"/>
                  </div>
            </form>
        </div>

    </div>

              <div id="kc-info" class="login-pf-signup">
                  <div id="kc-info-wrapper" class="">
            <div id="kc-registration-container">
                <div id="kc-registration">
                    <span>Nouvel utilisateur ? <a tabindex="6"
                                                 href="/realms/geoplateforme/login-actions/registration?client_id=gpf-apim&amp;tab_id=-kMEH58m_EA">Enregistrement</a></span>
                </div>
            </div>

                  </div>
              </div>
        </div>
      </div>

    </div>
  </div>
</body>
</html>"

Je me demande alors, comment puis-je me connecter à l’API depuis Python pour pouvoir réaliser le tutoriel mentionné ci-dessus. Est-ce qu’il y a une étape que je manque ? Sinon, faut-il utiliser un autre outil que Python ?

Merci d'avance pour votre aide,
Bonne journée

**Comment by Dolite** [comment]
Utilisez-vous la librairie [sdk_entrepot_gpf](https://pypi.org/project/sdk_entrepot_gpf/) ou une librairie standard pour faire des requêtes HTTP ? Le redirect pour l'authentification ne semble pas être correctement interprété. Au final, les requêtes API Entrepôt doivent être envoyées avec un token valide (récupéré sur le SSO géoplateforme). C'est sur ce workflow d'authentification que l'utilisation de la librairie dédiée peut faciliter les choses.

**Comment by ARainaud** [comment]
J'utilise une librairie standard pour les requêtes HTTP : urllib.request. Je n'avais pas connaissance de la librairie sdk_entrepot_gdf. Je vais essayer et je vous fais un retour. Merci !

**Comment by Dolite** [comment]
Les sites de documentation viennent d'être mis à jour. Le lien vers la documentation du SDK est désormais dans le menu du site des tutoriels : https://geoplateforme.github.io/sdk-entrepot/

Une recherche par étiquette a également été mise en place : https://geoplateforme.github.io/tutoriels/production/tags/

**Comment by ARainaud** [comment]
Merci pour ces éléments ! J'ai donc crée un fichier config.ini, cependant je ne suis pas sûr de comprendre quelle valeur mettre en face du "client_id". En effet, la définition "votre groupe d'appartenance" n'est pas très claire pour moi. J'ai testé différentes combinaisons en renseignant par exemple le nom de ma communauté, le nom technique de ma communauté, un _id de communauté se trouvant dans la réponse à https://data.geopf.fr/api/users/me sans succès.

Pouvez-vous m'indiquer ce qu'il faut renseigner pour ce 'client_id' et où est ce que je peux le trouver svp ?

**Comment by Dolite** [comment]
Voici un exemple de section `store_authentification` dans config.ini :

```
[store_authentification]
http_proxy=<si besoin>
https_proxy=<si besoin>
token_url=https://sso.geopf.fr/realms/geoplateforme/protocol/openid-connect/token
# Groupe d’appartenance
client_id=gpf-warehouse
client_secret=BK2G7Vvkn7UDc8cV7edbCnHdYminWVw2
# Votre login
login=<login>
# Votre mot de passe
password = <mdp>
# Si double authentification, mettre la clé ici, sans les espaces, sans quote autour
totp_key = SJWAJEVPMKQBXZ27WIQVT3RRT74VHBCD
```
Il faut qu'on améliore la documentation sur cette partie

**Comment by ARainaud** [comment]
Merci, ce "gpf-warehouse", où puis-je le trouver ? il n'est pas dans la réponse à https://data.geopf.fr/api/users/me

**Comment by ARainaud** [comment]
Le problème ne venait pas du 'client_id' mais d'une vérification SSL probablement bloquée par le proxy sur mon réseau.
