### ISSUE TITLE
Intégration données : l'import en base ne maintient pas la casse du libellé des champts

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#3]
### Entité(s) concernée(s)

upload

### Route API concernée

None

### Méthode de la route API

None

### Description détaillée du bug

La DREAL-N  a constaté que l'import en base postgresql ne maintient pas la casse du libellé des champs. Tout est transformé en minuscule( ex : libToto devient libtoto). Bug ou choix technique ? S'il s'agit d'un choix technique alors il faudra l'indiquer aux utilisateurs comme une contrainte.

**Comment by Dolite** [comment]
C'est un choix technique : tous les applicatifs s'appuyant sur Postgresql ne gère pas forcément les majuscules (noms des attributs entre quotes pour postgresql). On a donc préféré standardiser les noms des champs et des tables (pas d'accent, que des minuscule, pas de tirets...). On doit effectivement être transparents là dessus.

**Comment by Dolite** [comment]
C'est donc un travail de documentation à améliorer.

**Comment by Dolite** [comment]
https://geoplateforme.github.io/tutoriels/vecteur/base/integration/#declenchement-de-cette-execution
