### ISSUE TITLE
archive : dysfonctionnement

### ISSUE THREAD

**Issue by DEAL972** [Geoplateforme/geoplateforme.github.io#34]
### Entité(s) concernée(s)

check

### Route API concernée

/datastores/{datastore}/uploads/{upload}/checks

### Méthode de la route API

GET

### Description détaillée du bug

Pour une livraison de données déclarée avec "type": "ARCHIVE",
la commande GET /datastores/{datastore}/uploads/{upload}/checks ne renvoie que la vérification standard.
-> **Absence de vérification archive** et en conséquence (?)
 impossibilité d'utiliser la commande POST /datastores/{datastore}/configurations avec "type": "DOWNLOAD" pour les données en question (2 sets de données ont été testés, dont celui du tutoriel)

**Comment by Dolite** [comment]
Normalement, l'absence de vérification sur votre livraison ARCHIVE aurait du empêcher la création de l'exécution d'intégration de l'archive. L'exécution de traitement pour intégrer l'archive (pour passer d'un upload ARCHIVE à une stored data ARCHIVE) a été un succès ?

**Comment by Dolite** [comment]
Votre espace de travail n'a pas accès à la vérification Archive, c'est pour cela qu'elle n'est pas lancée sur votre livraison. Nous devons vous l'ajouter. Vous ne devez pas non plus avoir accès au traitement d'intégration d'archives. Pouvez vous me dire ce que vous avec comme réponse aux appels GET /datastores/{datastore}/checks et GET /datastores/{datastore}/processings ?

**Comment by DEAL972** [comment]
Pour GET /datastores/{datastore}/checks la réponse est:

[
  {
    "name": "Vérification vecteur",
    "description": "La vérification vecteur contrôle que les fichiers sont bien lisibles et en extraie l'étendue",
    "_id": "66ed8a1b-93d9-4fe9-a413-ab93d31b2964"
  },
  {
    "name": "Vérification standard",
    "description": "La vérification standard contrôle les signatures MD5 fournies",
    "_id": "ecb00ba0-eb42-427e-8418-f5d8a30e84ec"
  }
]

**Comment by DEAL972** [comment]
Pour GET /datastores/{datastore}/processings :

[
  {
    "name": "Intégration de données vecteur livrées en base",
    "description": "Ce traitement permet de stocker dans les bases de données PostgreSQL de la plateforme des données vecteurs livrées. Les formats pris en charge sont le CSV, le Shapefile, le Geopackage et le GeoJSON. Il est également possible de préciser un autre système afin de réaliser une reprojection à l'intégration.",
    "_id": "0de8c60b-9938-4be9-aa36-9026b77c3c96"
  }
]

**Comment by DEAL972** [comment]
Pour GET /datastores/{datastore}/checks la réponse est:

[
{
"name": "Vérification vecteur",
"description": "La vérification vecteur contrôle que les fichiers sont 
bien lisibles et en extraie l'étendue",
"_id": "66ed8a1b-93d9-4fe9-a413-ab93d31b2964"
},
{
"name": "Vérification standard",
"description": "La vérification standard contrôle les signatures MD5 
fournies",
"_id": "ecb00ba0-eb42-427e-8418-f5d8a30e84ec"
}
]


et pour GET /datastores/{datastore}/processings :

[
{
"name": "Intégration de données vecteur livrées en base",
"description": "Ce traitement permet de stocker dans les bases de 
données PostgreSQL de la plateforme des données vecteurs livrées. Les 
formats pris en charge sont le CSV, le Shapefile, le Geopackage et le 
GeoJSON. Il est également possible de préciser un autre système afin de 
réaliser une reprojection à l'intégration.",
"_id": "0de8c60b-9938-4be9-aa36-9026b77c3c96"
}
]


Le 26/01/2024 11:03, > notifications a écrit :

**Comment by DEAL972** [comment]
Il n'y a pas encore d'identifiant stored data car la procédure s'est 
arrêtée à l'étape traitement (processing):

POST /datastores/{datastore}/processings/executions
{
     "processing": "12cdc646-3976-4f18-b273-f34fca37e2a6",
     "inputs": {
         "upload": [
             "3fea5152-ce59-479e-ae4a-8f4e2d834e8f"
         ]
     },
     "output": {
         "stored_data": {
             "name": "deal972_eutrophisation_s",
             "storage_tags": ["ARCHIVE"]
        }
     }
}

Une tentative avait initialement été faite avec l'id_processing : 
0de8c60b-9938-4be9-aa36-9026b77c3c96
0de8c60b-9938-4be9-aa36-9026b77c3c96 (intégration postgre). 
Infructueuse.





Le 26/01/2024 11:15, > notifications a écrit :

**Comment by Dolite** [comment]
C'est bon. Pour que votre livraison soit bien vérifiée, vous pouvez la rouvrir et la refermer. Vous verrez ainsi les deux vérifications tourner. Vous aurez ensuite la possibilité d'utiliser le bon traitement, dont l'identifiant est dans le tutoriel.

**Comment by DEAL972** [comment]
Cela fonctionne maintenant. Merci.

Le 26/01/2024 11:39, > notifications a écrit :
