### ISSUE TITLE
Absence de service de diffusion

### ISSUE THREAD

**Issue by Medstaroc** [Geoplateforme/geoplateforme.github.io#40]
### Type de diffusion concernée

Service de téléchargement

### Accès concerné

Ouvert

### Description de l'erreur

Bonjour,

Sur notre entrepot Nantes Métropole, il nous manque les sevices de diffusion de téléchargement pour les données archive, et aussi les services de diffusion Raster pour nos orthophotographies.

datastore_id : 916d905c-6667-458e-9647-2cada7847245

Pourriez vous nous activer ces services ?
Merci 

Cordialement
Mohamed DARARI

**Comment by Dolite** [comment]
Je viens d'ajouter le endpoint DOWNLOAD à votre entrepôt. Désolé pour l'oubli.

**Comment by Medstaroc** [comment]
Merci pour l'activation du endpoint download, Il nous manque le service de diffusion WMS Raster principal.
ae042611-13eb-4a18-8d04-9b7604a031cc

**Comment by Dolite** [comment]
Décidément, il faudrait que je prenne plus le temps... WMS Raster et WMTS ajoutés.
