### ISSUE TITLE
Service de recherche : récupérer les couches Géoportail associés à un point géographique

### ISSUE THREAD

**Issue by meucamille** [Geoplateforme/geoplateforme.github.io#44]
### Vos questions

Bonjour,

J'utilisais l'ancien service "**look4**" et à partir de celui-ci, il m'était possible de recherche depuis un point géographique différentes informations sur ce point et notamment, voir les couches Géoportail qui lui étaient associés.

Pour donner un cas _concret_, je veux déterminer les couches Géoportail qui sont associés à ce point (exemple : point géographique placé dans le parc national de forêts) : 
`POINT (4.981613 47.873986)`

Le résultat attendu est que le point appartient à la couche Géoportail "Parcs nationaux" issue du service web "experts" avec comme clé "environnement".

D'après vos documentations de Géoplatforme, j'ai débuté avec votre service de recherche Géoplatforme à savoir ([Documentation recherche standard Géoplatforme](https://geoservices.ign.fr/documentation/services/services-geoplateforme/service-geoplateforme-de-recherche#72759)). 
mais je ne parviens pas à écrire une URL qui fasse la même chose qu'avec le service "look4" :

Exemple avec look4: 
`https://wxs.ign.fr/calcul/look4/user/search?match[geometry]=POINT(4.981613 47.873986)&indices=wwwLayers&method=fuzzy`

- **la clé "calcul"** : pour récupérer les informations
- **match[geometry]** = POINT(...) : pour spécifier ma recherche à un point géographique précis (format WKT)
- **indices = wwwLayers** : pour ne récupérer que les couches Géoportail en résultat
- **method = fuzzy** : pour effectuer une recherche précise

Est-ce que le service de recherche Géoplatforme me permet de rechercher à partir d'un point géographique, les couches Géoportail associés ? Est-ce un autre service ? 

Merci d'avance et vous souhaite une bonne journée.

**Comment by CorentinPeutin** [comment]
Bonjour, il n'est malheureusement pas possible de rechercher à partir d'une géométrie une couche Géoplateforme associée.
Mais, est-ce que vous avez une requête qui fonctionne de cette façon sur le Géoportail car la requête que vous fournissez dans le ticket renvoit une réponse vide ?

**Comment by meucamille** [comment]
Bonjour,

Tout d'abord merci de votre réponse :) !


> Mais, est-ce que vous avez une requête qui fonctionne de cette façon sur le Géoportail car la requête que vous fournissez dans le ticket renvoit une réponse vide ? 

Non la requête que j'ai mentionné sur votre ancien service ne fonctionnait pas avec le paramètre `match[geometry]` cependant je réussissais à avoir des réponses pertinentes lorsque je cherchais avec `match[fulltext]` et que je renseignais une adresse postale.

Je n'ai plus le résultat de cette requête mais de mémoire j'obtenais une liste de layers (limités) disponibles aux adresses correspondantes.
