### ISSUE TITLE
Flux WMS scan25 cle ign_scan_ws - balise <?xml version="1.0" encoding="UTF-8" ?> manquante

### ISSUE THREAD

**Issue by jpotel** [Geoplateforme/geoplateforme.github.io#46]
### Type de diffusion concernée

Service WMS Raster

### Accès concerné

Ouvert

### Description de l'erreur

Certains clients rencontrent des problèmes pour comprendre la réponse de la [requête getcapabilites](https://data.geopf.fr/private/wms-r?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&apikey=ign_scan_ws) du flux privé de diffusion des scan sous licence (scan25,...).
L'information ```<?xml version="1.0" encoding="UTF-8" ?>``` est manquante au début du xml.

**Comment by Dolite** [comment]
Cela a été pris en compte, nous vous tenons au courant de la correction. Merci pour votre remontée.

**Comment by Dolite** [comment]
C'est corrigé. Désolé pour l'oubli de réponse dans ce ticket.
