### ISSUE TITLE
Pas de modification possible du nom de table

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#5]
### Entité(s) concernée(s)

stored data

### Route API concernée

None

### Méthode de la route API

None

### Description détaillée du bug

La DREAL-N indique qu'il est possible de modifier le nom d'un store_data mais pas d'une table. 
Ca a posé un problème caril y a eu  une petite erreur de frappe dans le json de définition de la ressource vue qu'à la fin. Pour corriger , l'utilisateur aurait eu besoin à priori de tout refaire.

**Comment by Dolite** [comment]
L'API ne permet pas de modifier les données directement, elle ne manipule que des concepts entrepôt. La stored data en est un et son nom, purement informatif (non utilisé au niveau du stockage) peut donc être modifié. Si le nom de la table contient une erreur, plusieurs possibilité :

* Refaire la donnée
* Si c'est la diffusion WFS qui pose problème, la configuration WFS permet de modifier le nom exposé (native_name et public_name)
* Lorsque le traitement de dérivation vecteur sera disponible, il permettra de faire ce genre de modification via une exécution de traitement
