### ISSUE TITLE
Line 93 in Markdown file: expected token ',', got 'itinéraire' 

### ISSUE THREAD

**Issue by acogent** [Geoplateforme/geoplateforme.github.io#51]
### Tutoriel concerné

None

### Page concernée

https://geoplateforme.github.io/entrepot/production/composants/

### Description de l'erreur

Une coquille empeche l'affichage correct de la page  https://geoplateforme.github.io/entrepot/production/composants/

**Comment by Dolite** [comment]
C'est corrigé, merci pour la remontée.
