### ISSUE TITLE
Configuration DOWNLOAD impossible

### ISSUE THREAD

**Issue by FannyLecuy** [Geoplateforme/geoplateforme.github.io#54]
### Entité(s) concernée(s)

configuration

### Route API concernée

/datastores/{datastore}/configurations

### Méthode de la route API

POST

### Description détaillée du bug

Bonjour,

Je n'arrive pas à créer une configuration de type DOWNLOAD, j'ai toujours la réponse "bad request - erreur indéterminée dans le json". 
Pourtant le json est conforme au schema récupéré sur le swagger et même avec le json du tutoriel dont j'ai juste modifié les valeurs.
Le datastore (a77e0795-41be-4a44-af1f-e6f492512a85) a bien le droit de publier des archives et la stored_data (dcdd3cf5-9576-4b1f-a746-6c18e35af913) est bien de type 'ARCHIVE'.

Voici le corps de requête :
{
    "type": "DOWNLOAD",
    "name": "delmarDL",
    "layer_name": "DELMAR_DL",
    "type_infos": {
        "title": "Délimitations maritime",
        "abstract": "Délimitations maritimes françaises",
         "keywords": [
            "lignes de base droite", "ZEE", "mer territoriale", "zone contigue", "frontières maritimes", "plateau continental"
        ],
        "used_data": [
            {
                "sub_name": "delmar",
                "stored_data": "dcdd3cf5-9576-4b1f-a746-6c18e35af913"
            }
        ]
    }
}

Pouvez-vous m'éclairer sur ce qui ne va pas s'il vous plaît ?

**Comment by Dolite** [comment]
Bonjour,
Pouvez vous me dire quelle est l'erreur reçue ?

**Comment by FannyLecuy** [comment]
Bonjour,
J'ai "Erreur 400 Bad request, Erreur indéterminée dans le JSON".

**Comment by Dolite** [comment]
La configuration d'une diffusion DOWNLOAD a effectivement été modifiée pour avoir un service de téléchargement respectant le standard ATOM. Le tutoriel n'a pas été mis à jour, nous le faisons le plus vite possible. Veuillez nous excuser pour cet écart entre la documentation et l'implémentation.
Voici votre configuration au nouveau format :
```json
{
    "type": "DOWNLOAD",
    "name": "delmarDL",
    "layer_name": "DELMAR_DL",
    "type_infos":
    {
        "title":
        {
            "fr": "Délimitations maritime"
        },
        "abstract":
        {
            "fr": "Délimitations maritimes françaises"
        },
        "keywords":
        [
            "lignes de base droite",
            "ZEE",
            "mer territoriale",
            "zone contigue",
            "frontières maritimes",
            "plateau continental"
        ],
        "used_data":
        [
            {
                "sub_name": "delmar",
                "stored_data": "dcdd3cf5-9576-4b1f-a746-6c18e35af913"
            }
        ]
    }
}
```
Il est maintenant possible de fournir des titres et des résumés dans plusieurs langues.

De manière générale, cette erreur signale (de manière peu explicite je le reconnais) que la syntaxe n'est pas celle attendue pour un attribut. La documentation technique (swagger) à jour est [ici](https://data.geopf.fr/api/swagger-ui/index.html). Nous avons bien conscience que ce type de documentation n'est pas très accessible et c'est pourquoi nous essayons de tenir à jour des tutoriels concrets.

Merci beaucoup pour votre retour.

**Comment by Dolite** [comment]
Documentation mise à jour : https://geoplateforme.github.io/tutoriels/production/archive/base/publication/
