### ISSUE TITLE
Supression d'une fiche de métadonnée

### ISSUE THREAD

**Issue by NicoLeclercIGN** [Geoplateforme/geoplateforme.github.io#57]
### Documentation concernée

Gestion des métadonnées

### Description du manque de détail

Subtilité sur al mécanique de supression de la métadonnée : 
L'action sur la route de delete ne suffit pas, il faut d'abord jouer sur la route de dépublication qui est un POST.
Donc : step 1 : POST
[/datastores/{datastore}/metadata/unpublication](https://data.geopf.fr/api/swagger-ui/index.html#/M%C3%A9tadonn%C3%A9es/unpublish)
et step 2 : DELETE
[/datastores/{datastore}/metadata/{metadata}](https://data.geopf.fr/api/swagger-ui/index.html#/M%C3%A9tadonn%C3%A9es/delete_6)

si step2  direct, on prend une  409 : {  "error": "Conflict",  "error_description": [    "La métadonnée est encore publiée ou en cours de (dé)publication sur certains endpoints"  ]

}

**Comment by Dolite** [comment]
Le prérequis de la dépublication avant suppression est décrit ici : https://geoplateforme.github.io/tutoriels/production/complement/metadonnees/publication/#supprimer-une-metadonnee . Il faudrait l'afficher plus explicitement, sous forme d'un encadré warning par exemple ?

**Comment by NicoLeclercIGN** [comment]
Ach ! j'ai pêché par orgueil et j'ai by-passé la doc pour une fois. J'ai été puni !
Sujet clos donc
Merci
