### ISSUE TITLE
Impossible d'accéder à la doc openapi

### ISSUE THREAD

**Issue by Guts** [Geoplateforme/geoplateforme.github.io#58]
### Tutoriel concerné

None

### Page concernée

https://geoplateforme.github.io/entrepot/production/openapi/

### Description de l'erreur

Salut,

En cliquant sur le menu "OpenAPI Entrepôt" on arrive sur cette erreur : ![image](https://github.com/user-attachments/assets/b2c9193c-fbc5-4274-b86d-d1812a8ec73a)

**Comment by Dolite** [comment]
C'est corrigé :) Petite erreur d'URL, qui pointait toujours sur le fichier openapi de l'environnement de qualification.

**Comment by Guts** [comment]
En effet. Merci pour la réactivité !
