### ISSUE TITLE
Difficulté pour créer le SLD compatible GPF

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#8]
### Entité(s) concernée(s)

configuration

### Route API concernée

None

### Méthode de la route API

None

### Description détaillée du bug

La DREAL-N a eu des difficultés pour créer un sld compatible.
Il est indiqué dans les tutoriels un outil que l'utilisateur n'a jamais réussi à trouver et à installer sur son poste windows.
Apparemment il faudrait en en fait installer un geoserver complet pour pouvoir utiliser cet outil.

L'utilisateur a utilisé  le plugin QGIS "GeoCat Bridge" pour créer un sld qui fonctionne sur la géoplateforme

**Comment by Dolite** [comment]
L'écriture de SLD n'est effectivement pas simple : il existe plusieurs outils mais aucun n'est parfait. L'export de QGis en SLD n'est pas toujours compatible, geostyler non plus... Je vais ajouter GeoCat Bridge dans les propositions si il semble mieux fonctionner.

**Comment by Dolite** [comment]
https://geoplateforme.github.io/tutoriels/vecteur/base/gestion_statique/#generation-dun-sld
