### ISSUE TITLE
Tutoriel WMS à améliorer

### ISSUE THREAD

**Issue by IGNF-Xavier** [Geoplateforme/geoplateforme.github.io#9]
### Tutoriel concerné

Gestion d'archives - Alimentation et diffusion simple

### Description de l'erreur

La DREAL-N indique qu'en suivant le tutoriel, ce dernier a obtenu un WMS avec les trois dataset dans une même couche alors que que le souhait était d'avoir une couche WMS par dataset.
Le travail a dû  être refait le travail couche par couche.

**Comment by Dolite** [comment]
J'ajoute un warning

**Comment by Dolite** [comment]
https://geoplateforme.github.io/tutoriels/vecteur/base/publication_wms/#configuration-de-la-diffusion-wms
